### PR TITLE
Update role.java to correct deserialization issue

### LINKED ISSUE #365: Role Enum does not have reverse lookup
**Describe the bug**
Role Enum does not have reverse lookup therefore incoming JSON data cannot be mapped to correct role causing a
"Cannot deserialize value of type `org.zendesk.client.v2.model.Role` from String "end-user": not one of the values accepted for Enum class: [AGENT, ADMIN, END_USER]
 at [Source: UNKNOWN; line: -1, column: -1] (through reference chain: java.lang.Object[][0]->org.zendesk.client.v2.model.User["role"])"

**To Reproduce**
1. send GET request to /api/v2/users/show_many.json?ids={CommaSeparatedUserIds}
2. you should be able to map the response to a Zendesk User model

**Expected behavior**
Enum "end-user" should reverse lookup to "END_USER"

### PR DESCRIPTION
**Pull request by ajarnold87**
Fixes #365

### CODE REVIEW

**Comment by ajarnold87** [comment]
@aheritier @duemir any chance we can get this reviewed. I am working on a project and need this fix implemented before i can finish.

**Comment by duemir** [comment]
@ajarnold87 the change is passing CI. The test failures look related. Tests like `RealSmokeTest.getUsersIncrementally` and `RealSmokeTest.getUsers` fail whereas they pass on the `master` branch.

**Comment by ajarnold87** [comment]
Are you talking about this error? It seems like there are ~60 of these in the tests and all with the same error of missing scheme. 
`getUsersIncrementally(org.zendesk.client.v2.RealSmokeTest)  Time elapsed: 0.016 sec  <<< ERROR!
java.lang.IllegalArgumentException: /api/v2/incremental/users.json?start_time=0 could not be parsed into a proper Uri, missing scheme
	at org.asynchttpclient.uri.Uri.create(Uri.java:70)
	at org.asynchttpclient.uri.Uri.create(Uri.java:62)
	at org.asynchttpclient.RequestBuilderBase.setUrl(RequestBuilderBase.java:147)
	at org.zendesk.client.v2.Zendesk.reqBuilder(Zendesk.java:2361)
	at org.zendesk.client.v2.Zendesk.req(Zendesk.java:2343)
	at org.zendesk.client.v2.Zendesk.access$1100(Zendesk.java:101)
	at org.zendesk.client.v2.Zendesk$PagedIterable$PagedIterator.hasNext(Zendesk.java:2950)
	at org.zendesk.client.v2.RealSmokeTest.getUsersIncrementally(RealSmokeTest.java:1014)`

**Comment by duemir** [comment]
@ajarnold87 thank you for the investigation. Let me take a look.

**Comment by duemir** [comment]
The variables are injected from the repository secrets and it looks like the secrets are not shared to the PRs from the forks. @aheritier wdyt?

**Comment by aheritier** [comment]
effectively @duemir I didn't know that but it doesn't support external PRs to protect the secrets AFAIU :(
I confirm that our integration tests aren't passing @ajarnold87 https://gist.github.com/aheritier/8cea10954e242bbd2231120aa9b53fe8

**Pull request closed without merging**
