### PR TITLE
Create maven-publish.yml

### PR DESCRIPTION
**Pull request by Iniyethawe2**
.github/workflows/maven-publish.yml

### CODE REVIEW

**Review by aheritier — COMMENTED** [review]
I am not sure cc @duemir 
The maven community doesn't really like this GH feature which is creating a lot of GitHub repos everywhere.
This project is configured to have its releases synced to maven central and the snapshots are available (I think) on oss.sonatype.org
What are you expecting from this change @Iniyethawe2 ?
Which problem does it solve for you ?
cc @johnou @Dohbedoh

**Comment by johnou** [comment]
I prefer Maven central.

**Comment by aheritier** [comment]
@johnou I am still working internally to get the repo  moved to an org where you and external contributors are allowed (I am sorry)

**Comment by aheritier** [comment]
I configured a GitHub action to build / test / and analyze the project with sonarCloud
It will give a better visibility on the build for the team and contributors

**Pull request closed without merging**
