### PR TITLE
Support the 'Content Tags' resource in the Zendesk API - resolves #559

### LINKED ISSUE #559: Add support for the Content Tag resource (in the Help Center API)
Content Tags can be added to posts and articles to loosely group them together.
The client does not currently expose this API resource.

The resource is a small object {id, name, createdDate, updatedDate}
The API supports CRUD & some searching

**Describe the solution you'd like**
The client to expose CRUD & searching on this resource

**Additional context**
API documentation: https://developer.zendesk.com/api-reference/help_center/help-center-api/content_tags/
Article about how they are used: https://support.zendesk.com/hc/en-us/articles/4848925672730

I'm currently working on building a PR to implement this feature request

### PR DESCRIPTION
**Pull request by andy-may-at**
Content Tags can be added to posts and articles to loosely group them together.
The resource is a small object {id, name, createdDate, updatedDate}
The API supports CRUD & some searching

**Additional context**
API documentation: https://developer.zendesk.com/api-reference/help_center/help-center-api/content_tags/
Article about how they are used: https://support.zendesk.com/hc/en-us/articles/4848925672730

### CODE REVIEW

**Comment by PierreBtz** [comment]
@andy-may-at I'll let you refresh and finish up on this branch, then I'll merge and cut a new release.

**Review by PierreBtz — DISMISSED** [review]
Lgmt, nice work.
I'm taking the library to commit the fix on the javadoc to be able to merge and release

**Review by PierreBtz — APPROVED** [review]

**Comment by andy-may-at** [comment]
@PierreBtz - while doing this PR, I noticed that there's a fair bit of inconsistent whitespace in Zendesk.java, which made my IntelliJ keep try to be helpful & fix it (which I didn't want to do as part of this PR).
 
Might be worth doing an auto-format of the whole file if you've got an IDE with appropriate code-style settings for the project :)

**Comment by PierreBtz** [comment]
@andy-may-at indeed I noticed that too (project has a lot of history with a lot of different contributors and maintainers). 
I was recently contributing to a project that was using https://github.com/diffplug/spotless/tree/main/plugin-maven to keep things clean (it fails the build if the formatting is messed up). I had something like that in mind.

**Comment by andy-may-at** [comment]
In Kotlin-land I've been using Kotlinter, which enforces the code style that you have in your .editorconfig file
That behaviour's been good for having a single source of truth for code style.

Not used it myself, but this maven plugin seems to do that:
https://ec4j.github.io/editorconfig-maven-plugin/

**Comment by PierreBtz** [comment]
Interesting, I wasn't aware editorconfig was providing a Maven plugin. I'll have a look.

**Pull request merged**
